name = "gtd-space-station-168-api"
main = "src/index.js"
compatibility_date = "2024-08-10"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "gtd-db"
database_id = "e31e57f7-4148-420a-bce5-60d3fb00fa00"
migrations_dir = "./migrations"

[observability]
enabled = true
